packages:
  - packages/**

onlyBuiltDependencies:
  - esbuild

catalog:
  "@types/hast": ^3.0.4
  "@types/mdast": ^4.0.4
  "@types/node": ^25.2.3
  "@types/unist": ^3.0.3
  hastscript: ^9.0.1
  mdast-util-find-and-replace: ^3.0.2
  mdast-util-math: ^3.0.0
  micromark-util-symbol: ^2.0.1
  micromark-util-types: ^2.0.2
  rehype-parse: ^9.0.1
  rehype-stringify: ^10.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  remark-stringify: ^11.0.0
  shiki: ^3.22.0
  unified: ^11.0.5
  unist-builder: ^4.0.0
  unist-util-visit: ^5.1.0
  vitest: ^4.0.18
