packages:
  - packages/**

onlyBuiltDependencies:
  - esbuild

catalog:
  "@types/node": ^25.2.3
  "@types/mdast": ^4.0.4
  "@types/unist": ^3.0.3
  remark-parse: ^11.0.0
  remark-stringify: ^11.0.0
  remark-rehype: ^11.1.2
  rehype-stringify: ^10.0.1
  mdast-util-find-and-replace: ^3.0.2
  unified: ^11.0.5
  unist-builder: ^4.0.0
  unist-util-visit: ^5.1.0
  vitest: ^4.0.18
